### ISSUE TITLE
Confirming gnaf addresses header prefix in header.ttl

### ISSUE THREAD

**Issue by wjfrancis** [CSIRO-enviro-informatics/addressescatchments-linkset#1]
header.ttl

@prefix g: <http://linked.data.gov.au/dataset/gnaf/addresses/> .

should it be the following?

@prefix g: <http://linked.data.gov.au/dataset/gnaf/address/> .

The redirect rules then would support correctly redirection from the linked.data.gov.au domain to the gnafld one.

e.g. http://linked.data.gov.au/dataset/gnaf/addresses/GAACT714845933 is currently not resolving but http://linked.data.gov.au/dataset/gnaf/address/GAACT714845933 would.

**Comment by nicholascar** [comment]
Well spotted Will! A Typo. Fixed now with Commit https://github.com/CSIRO-enviro-informatics/addressescatchments-linkset/commit/0cdbd4edc5582722bd520d1098b9a358a3563876
