### ISSUE TITLE
void:subjectsTarget typo

### ISSUE THREAD

**Issue by edmondchuc** [CSIRO-enviro-informatics/addressescatchments-linkset#3]
In https://github.com/CSIRO-enviro-informatics/addressescatchments-linkset/blob/master/header.ttl, should the predicate `void:subjectTarget` be `void:subjectsTarget`? 

I noticed it when I was writing a SPARQL query for loci.cat's Linkset landing page.

Reference: http://vocab.deri.ie/void#subjectsTarget
@nicholascar

**Comment by nicholascar** [comment]
fixed with commit https://github.com/CSIRO-enviro-informatics/addressescatchments-linkset/commit/8f70bf463b8e4ff47cb1b157dcc0439a56654ad2
