### ISSUE TITLE
subjectsTarget and objectsTarget wrong way around

### ISSUE THREAD

**Issue by edmondchuc** [CSIRO-enviro-informatics/addressescatchments-linkset#4]
Should be:
 ` void:objectsTarget <http://linked.data.gov.au/dataset/geofabric> ;`
 ` void:subjectsTarget <http://linked.data.gov.au/dataset/gnaf> .`

in the `header.ttl`.

**Comment by ashleysommer** [comment]
@edmondchuc 
I noticed that last week. I copied the header.ttl from this linkset to use as the basis of the meshblockscontractedcatchments-linkset header.
I didn't change it. As a result, the object and subject targets are the wrong way around in the meshblockscontractedcatchments linkset too.
